package selenium;

// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
public class DefaultSuiteTest01 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testdemo() {
        driver.get("https://ceshiren.com/");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
//            e.printStackTrace();
//            System.out.println();
        }
        driver.manage().window().setSize(new Dimension(515, 300));
        driver.findElement(By.cssSelector(".d-button-label:nth-child(2)")).click();
        driver.findElement(By.id("ember189")).click();
        driver.findElement(By.id("login-account-password")).click();
        driver.findElement(By.cssSelector("#login-button > .d-button-label")).click();
    }
}
